#spring:
#  task:
#    scheduling:
#      pool:
#        size: 5


management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*" #打开所有的监控点

server:
  servlet:
    context-path: /imooc
  port: 8000
